
"""
===============================================================================
05_HRV_FEATURES.PY
===============================================================================

Temporal AI for ECG-Based Event Detection and Short-Horizon Prediction


Minute-level HR / HRV feature extraction from saved R-peaks.

Important:
    - Does NOT reread or preprocess the ECG.
    - Uses the R-peaks already generated by 04_preprocessing.py.
    - RR artifacts are handled only for feature calculation.
    - Original R-peak / RR files are never modified.
    - Features are calculated independently for each record.
    - No apnea labels are used here.
===============================================================================
"""

from pathlib import Path
import numpy as np
import pandas as pd


# =============================================================================
# CONFIGURATION
# =============================================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/ecg_temporal_ai"
)

PREPROCESSING_DIR = (
    PROJECT_DIR
    / "outputs"
    / "preprocessing"
)

OUTPUT_DIR = (
    PROJECT_DIR
    / "outputs"
    / "features"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

FS = 100.0

MINUTE_SECONDS = 60.0

# Physiological/artifact screening limits.
RR_MIN_SEC = 0.30
RR_MAX_SEC = 2.00

# Minimum number of valid RR intervals required
# before calculating HRV statistics.
MIN_VALID_RR = 10

RECORDS = [
    "a01", "a02", "a03", "a05", "a06", "a07", "a08", "a09",
    "a11", "a12", "a13", "a14", "a15", "a16", "a18", "a19",
    "a20", "b01", "b02", "b04", "b05", "c01", "c02", "c03",
    "c04", "c06", "c07", "c08", "c09", "c10"
]


# =============================================================================
# HR / HRV CALCULATIONS
# =============================================================================

def calculate_minute_features(
    rpeak_samples,
    fs=FS,
    minute_seconds=MINUTE_SECONDS,
):
    """
    Convert R-peaks into minute-level HR/HRV features.

    RR interval is assigned to the minute containing the SECOND
    R-peak of that interval.
    """

    rpeak_samples = np.asarray(
        rpeak_samples,
        dtype=int
    )

    if len(rpeak_samples) < 2:
        return pd.DataFrame()

    # R-peak times in seconds.
    peak_times = rpeak_samples / fs

    # Successive RR intervals.
    rr = np.diff(peak_times)

    # Time associated with each RR interval:
    # use the time of the second R-peak.
    rr_times = peak_times[1:]

    # Record-level artifact mask.
    valid_rr = (
        np.isfinite(rr)
        &
        (rr >= RR_MIN_SEC)
        &
        (rr <= RR_MAX_SEC)
    )

    minute_indices = np.floor(
        rr_times / minute_seconds
    ).astype(int)

    rows = []

    for minute in np.unique(minute_indices):

        mask = (
            minute_indices == minute
        )

        rr_all = rr[mask]
        valid_all = valid_rr[mask]

        rr_valid = rr_all[
            valid_all
        ]

        n_rr_total = len(rr_all)
        n_rr_valid = len(rr_valid)

        if n_rr_total == 0:
            continue

        invalid_fraction = (
            1.0
            -
            n_rr_valid / n_rr_total
        )

        # Not enough valid beats for reliable HRV.
        if n_rr_valid < MIN_VALID_RR:

            rows.append({
                "minute": minute,
                "mean_rr_sec": np.nan,
                "median_rr_sec": np.nan,
                "mean_hr_bpm": np.nan,
                "median_hr_bpm": np.nan,
                "sdnn_sec": np.nan,
                "rmssd_sec": np.nan,
                "pnn50": np.nan,
                "cv_rr": np.nan,
                "n_rr_total": n_rr_total,
                "n_rr_valid": n_rr_valid,
                "rr_invalid_fraction": invalid_fraction,
                "feature_valid": 0,
            })

            continue

        # ---------------------------------------------------------------------
        # Time-domain HR / HRV
        # ---------------------------------------------------------------------

        mean_rr = np.mean(
            rr_valid
        )

        median_rr = np.median(
            rr_valid
        )

        mean_hr = (
            60.0 / mean_rr
        )

        median_hr = (
            60.0 / median_rr
        )

        # SDNN
        sdnn = np.std(
            rr_valid,
            ddof=1
        )

        # RMSSD
        if len(rr_valid) >= 2:

            successive_diff = np.diff(
                rr_valid
            )

            rmssd = np.sqrt(
                np.mean(
                    successive_diff ** 2
                )
            )

        else:

            rmssd = np.nan

        # pNN50
        if len(rr_valid) >= 2:

            nn50 = np.sum(
                np.abs(
                    np.diff(rr_valid)
                ) > 0.050
            )

            pnn50 = (
                nn50
                /
                (len(rr_valid) - 1)
            )

        else:

            pnn50 = np.nan

        # Coefficient of variation
        cv_rr = (
            sdnn / mean_rr
            if mean_rr > 0
            else np.nan
        )

        rows.append({
            "minute": minute,
            "mean_rr_sec": mean_rr,
            "median_rr_sec": median_rr,
            "mean_hr_bpm": mean_hr,
            "median_hr_bpm": median_hr,
            "sdnn_sec": sdnn,
            "rmssd_sec": rmssd,
            "pnn50": pnn50,
            "cv_rr": cv_rr,
            "n_rr_total": n_rr_total,
            "n_rr_valid": n_rr_valid,
            "rr_invalid_fraction": invalid_fraction,
            "feature_valid": 1,
        })

    return pd.DataFrame(rows)


# =============================================================================
# PROCESS ONE RECORD
# =============================================================================

def process_record(record_id):

    rpeak_file = (
        PREPROCESSING_DIR
        / f"{record_id}_rpeaks.csv"
    )

    if not rpeak_file.exists():

        raise FileNotFoundError(
            f"Missing R-peak file: {rpeak_file}"
        )

    print()
    print("=" * 80)
    print(
        f"HR/HRV FEATURE EXTRACTION: {record_id}"
    )
    print("=" * 80)

    rpeak_df = pd.read_csv(
        rpeak_file
    )

    if "sample" not in rpeak_df.columns:

        raise ValueError(
            f"'sample' column not found in {rpeak_file}"
        )

    rpeaks = rpeak_df[
        "sample"
    ].dropna().astype(int).values

    features = calculate_minute_features(
        rpeaks,
        fs=FS
    )

    if features.empty:

        raise ValueError(
            f"No HR/HRV features generated for {record_id}"
        )

    features.insert(
        0,
        "subject_id",
        record_id
    )

    output_file = (
        OUTPUT_DIR
        / f"{record_id}_hrv_features.csv"
    )

    features.to_csv(
        output_file,
        index=False
    )

    valid_fraction = (
        features["feature_valid"].mean()
    )

    print(
        "R-peaks:",
        len(rpeaks)
    )

    print(
        "Minute feature rows:",
        len(features)
    )

    print(
        "Valid feature minutes:",
        round(
            valid_fraction * 100,
            2
        ),
        "%"
    )

    print(
        "Saved:",
        output_file
    )

    return features


# =============================================================================
# MAIN
# =============================================================================

def main():

    print("=" * 80)
    print(
        "ECG TEMPORAL AI — HR/HRV FEATURE EXTRACTION"
    )
    print("=" * 80)

    all_features = []

    for record_id in RECORDS:

        try:

            features = process_record(
                record_id
            )

            all_features.append(
                features
            )

            print(
                f"[SUCCESS] {record_id}"
            )

        except Exception as exc:

            print(
                f"[FAILED] {record_id}: {exc}"
            )

    if not all_features:

        raise RuntimeError(
            "No records were successfully processed."
        )

    combined = pd.concat(
        all_features,
        ignore_index=True
    )

    combined_file = (
        OUTPUT_DIR
        / "all_records_hrv_features.csv"
    )

    combined.to_csv(
        combined_file,
        index=False
    )

    print()
    print("=" * 80)
    print("HR/HRV FEATURE EXTRACTION COMPLETE")
    print("=" * 80)

    print(
        "Total feature rows:",
        len(combined)
    )

    print(
        "Records:",
        combined["subject_id"].nunique()
    )

    print(
        "Combined file:",
        combined_file
    )


if __name__ == "__main__":
    main()
